### ISSUE TITLE
Products with multiple variants

### ISSUE THREAD

**Issue by maherelaridi** [Cam/Shopify-Theme-Framework#34]
Does this template support products with multiple options?
Thank you for this template btw. It works great!

**Comment by ineptian** [comment]
Hey Cam,

I see this issue was solved by maherelaridi but I am having trouble figuring it out myself.

Basically I have a few product variants but selecting between them in the drop down does not actually change the price displayed. I am guessing it is just an issue with the jquery somewhere but I can't quite find it.

The price displayed used to just default to the lowest price, i changed the code to select the first available variant from the list so now it show the proper price when the page loads, but selecting between variants does nothing. Any help with this issue would be much appreciated, it is one of the last road blocks I am running into with my product.liquid.

You can see the example here: http://asterisk-2.myshopify.com/collections/protection/products/sample-product-2

pw: whaick

Thanks again.

**Comment by Cam** [comment]
Hi @ineptian. Most of this theme is a Foundation-ized version of the Minimal theme by Shopify (albeit a much older version). I would recommend grabbing the new scripting from that and merging it in to your product pages https://themes.shopify.com/themes/minimal/styles/fashion

**Comment by hajeshcorra** [comment]
Hello, 

For a product we have created two set of option option-1 and option-2. Is it possible to show option-1 as a select box and option-2 as a checkbox
